export const drumPads = [
  {
    keycap: "Q",
    titleOne: "Saxophone 1",
    titleTwo: "Flute 1",
    soundUrlOne: require("./soundSamples/072278_saxophone-1-46459.mp3"),
    soundUrlTwo: require("./soundSamples/bansuri_flute_rag_jog-46424.mp3"),
  },
  {
    keycap: "W",
    titleOne: "note C6",
    titleTwo: "note C3",
    soundUrlOne: require("./soundSamples/c3-95007.mp3"),
    soundUrlTwo: require("./soundSamples/c6-102822.mp3"),
  },
  {
    keycap: "E",
    titleOne: "note do",
    titleTwo: "piano 1",
    soundUrlOne: require("./soundSamples/do-80236.mp3"),
    soundUrlTwo: require("./soundSamples/elegant-piano-logo-tranquility-relaxation-medicine-153281.mp3"),
  },
  {
    keycap: "A",
    titleOne: "note fa",
    titleTwo: "drum 1",
    soundUrlOne: require("./soundSamples/fa-78409.mp3"),
    soundUrlTwo: require("./soundSamples/failure-drum-sound-effect-2-7184.mp3"),
  },
  {
    keycap: "S",
    titleOne: "ringtone",
    titleTwo: "piano 2",
    soundUrlOne: require("./soundSamples/family-store-logo-13175.mp3"),
    soundUrlTwo: require("./soundSamples/glad-piano-logo-13394.mp3"),
  },
  {
    keycap: "D",
    titleOne: "note la",
    titleTwo: "piano 3",
    soundUrlOne: require("./soundSamples/la-80237.mp3"),
    soundUrlTwo: require("./soundSamples/logo-soft-piano-new-product-opening-trial-132311.mp3"),
  },
  {
    keycap: "Z",
    titleOne: "piano 4",
    titleTwo: "sample",
    soundUrlOne: require("./soundSamples/piano-g-6200.mp3"),
    soundUrlTwo: require("./soundSamples/punch-boxing-02wav-14897.mp3"),
  },
  {
    keycap: "X",
    titleOne: "note e6",
    titleTwo: "theme song",
    soundUrlOne: require("./soundSamples/scale-e6-14577.mp3"),
    soundUrlTwo: require("./soundSamples/select-sound-thing-100628.mp3"),
  },
  {
    keycap: "C",
    titleOne: "electronic",
    titleTwo: "trumpet 1",
    soundUrlOne: require("./soundSamples/simple-hi-tech-logo-13774.mp3"),
    soundUrlTwo: require("./soundSamples/trumpet-e4-14829.mp3"),
  },
];
